# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 488e3c67df4e40dcb8a2915a992b94840d3d7a2d5705e897204e62a8d6bbd66bf70c52e503ead347b505c3fc66cd8d06e908d749b802a6385cfd99a62e568c6c

test:
  secret_key_base: 026a56b209bf0e3c4759271c726f0a3792ba3c366c55bf9a09c5ca6abd37447a13d951767eee7f0c84caeb95d97898b5075d47143c5a3a01e7f6b221f3c7a978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
